### ISSUE TITLE
automake start of docker daemon

### ISSUE THREAD

**Issue by geeksupport1** [LongLiveCHIEF/wsl2-docker-for-win#5]
https://medium.com/faun/docker-running-seamlessly-in-windows-subsystem-linux-6ef8412377aa

**Comment by LongLiveCHIEF** [comment]
closing in favor of #2 

@geeksupport1 the windows task scheduler is what I've tinkered with also, and what I was referring to when I mentioned "starting from the windws side of things".

I've had a few issues with making this task reliable though, and I need to write a better script that I can load into the task scheduler to take care of those inconsistencies.

Honestly, I was hoping to just wait for the docker wsl2 tech preview to work for windows 10 home (opened [GH 4586](https://github.com/docker/for-win/issues/4586) for this), since it would undoubtedly be a feature that would be in the docker desktop solution, and I'd rather not have a crappier duplicate bit of functionality that will be obsolete as soon as they solve the issue mentioned above.
